'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Company
    Public Property ID As Integer
    Public Property Name As String
    Public Property Address As String
    Public Property City As String
    Public Property Phone As String
    Public Property Zip As String
    Public Property Misc As String

    Public Overridable Property Contacts As ICollection(Of Contact) = New HashSet(Of Contact)
    Public Overridable Property Quotes As ICollection(Of Quote) = New HashSet(Of Quote)

End Class
