'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Database
	Inherits DbContext

	Public Sub New()
		MyBase.New("name=Database")
	End Sub

	Public Overridable Property Companies() As DbSet(Of Company)
	Public Overridable Property Contacts() As DbSet(Of Contact)
	Public Overridable Property Quotes() As DbSet(Of Quote)
	Public Overridable Property Notes() As DbSet(Of Note)
	Public Overridable Property QuoteLines() As DbSet(Of QuoteLine)
	Public Overridable Property Settings() As DbSet(Of Setting)

End Class
